### ISSUE TITLE
Error getting info in the 2016 media

### ISSUE THREAD

**Issue by jorgecis** [maxpat78/ImagePyX#1]
Hi,

   I found an issue using the windows 2016 media, the xml looks incomplete or with garbage

python ImagePyX.py  --info /media/sr3/sources/install.wim
Opening WIM unit...
Compression is LZX

WIM Information:
----------------
Path:           /media/sr3/sources/install.wim
GUID:           {18b148ab-6ab8-45ea-95cc-cb5186a04d7e}
Image Count:    1
Compression:    LZX
Part Number:    1/1
Attributes:     40082

Available Image choices:
------------------------
Traceback (most recent call last):
  File "ImagePyX.py", line 107, in <module>
    info(opts, args)
  File "/root/ImagePyX-master/SSWIMM/SSWIMMI.py", line 88, in info
    xml = minidom.parse(fp)
  File "/usr/lib64/python2.7/xml/dom/minidom.py", line 1918, in parse
    return expatbuilder.parse(file)
  File "/usr/lib64/python2.7/xml/dom/expatbuilder.py", line 928, in parse
    result = builder.parseFile(file)
  File "/usr/lib64/python2.7/xml/dom/expatbuilder.py", line 207, in parseFile
    parser.Parse(buffer, 0)
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 1, column 13

**Comment by maxpat78** [comment]
Can you provide here the XML from such WIM?
I'll take a look and eventually fix it, but very slowly (perhaps it could be that actual WIM/XML format was upgraded in the meantime; also, wimlib support isn't aligned to new library releases and it lacks LZMS support). Today I use myself wimlib-imagex, a very fast and reliable tool!

**Comment by jorgecis** [comment]
I did a pull request, I think that the problem is the read function reads too much, I change the code to read the exactly amount of bytes.
